[package]
name = "bitcoin-address-utils"
version = "1.0.7"
description = "This package is intended to be a plug and play bitcoin address generator and utils to manage bitcoin address on motoco and Internet Computer"
repository = "https://github.com/Universelle-io/bitcoin-address-utils"
keywords = [ "bitcoin", "address", "generator" ]
license = "MIT"

[dependencies]
bitcoin = "0.1.1"
sha2 = "0.1.0"
base16 = "1.0.0"

[dev-dependencies]
test = "2.1.1"