[package]
name = "bitcoin"
version = "0.1.1"
description = "Algorithms for bitcoin integration"
repository = "https://github.com/dfinity/motoko-bitcoin"
keywords = [ "bitcoin" ]
license = "Apache-2.0"

[dependencies]
base = "0.13.5"
sha2 = "0.1.0"

[dev-dependencies]
test = "2.0.0"

[toolchain]
wasmtime = "22.0.0"
moc = "0.12.1"
pocket-ic = "1.0.0"
